version: '3.6'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./lotus_db:/lotus/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

